version: '3.7'
x-django: &django
  volumes:
  - ./src/project/settings/local.py:/code/src/project/settings/local.py
  image: "${DJANGO_IMAGE}:${DJANGO_IMAGE_VERSION}"
services:
  elasticsearch:
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms4g -Xmx4g}
  django:
    <<: [ *django ]
  celery:
    <<: [ *django ]
  celerybeat:
    <<: [ *django ]
  db:
    volumes:
      - ./prod/pg-tune.sh:/docker-entrypoint-initdb.d/z_pg-tune.sh
      - postgresql:/var/lib/postgresql/data
  backup:
    image: "corpusops/dbsmartbackup:pgrouting-10-2.5-2.6"
    restart: always
    volumes:
    - backupdb-dumps:/var/db_smart_backup/
    - backupdb-logs:/var/db_smart_backup/logs/
volumes:
  backupdb-logs:
  backupdb-dumps:
